### PR TITLE
Stop at 20 MB file size logged or after 190 Minutes

### PR DESCRIPTION
**Pull request by Amerlander**

### CODE REVIEW

**Comment by rzbrk** [comment]
I would love to see this features added to play with.
Are the features already tested? If not, establish dedicated "feature branch" and merge it with branch main after testing/verification.

**Review by rzbrk — COMMENTED** [review]
Why? I liked this feature. The Calliope Mini Program gets a "signal" this way, that the Python script on the Raspberry Pi is ready to accept the data from the Calliope Mini. This way, no data is lost.

**Comment by joernalraun** [comment]
> [373cd8f](https://github.com/calliope-edu/CalliopEO_AstroPi/commit/373cd8ffdca87d79155fb80ad281c2001d03f987)
> Why? I liked this feature. The Calliope Mini Program gets a "signal" this way, that the Python script on the Raspberry Pi is ready to accept the data from the Calliope Mini. This way, no data is lost.

This was made due to the fact that there should be no serial read in that direction, at least that's what we all had heard in the last meeting. However, as we will check all files, we can use this option for the reason you described and make sure it can't be used in any other way.

**Comment by Amerlander** [comment]
Also to keep this feature we I think we would have to change line 84 and 85, so it gets inside the wihle:
```
while True:
    ser.write(b'@START@\r\n')
  ```
  After flashing the mini is unavailable an unknown amount of time. So when we send the `@START@` right after copying the file over there is a high risk the start signal never reaches the mini. Therefore we would have to send again and again until an answer is received.
 
But the Pi has no job do to, so it will be ready imediately after flashin. So there is no reasing the send some sinc signal, the mini can just start whenever it wants. Also the mini is passive, so if there some error the mini would not be able to do something to solve it. The Pi is the only part who could do something like reflaashing/starting the mini.

I also like the idea of keping both in Sync and make sure both are ready to send and receive. But in this case I feel like it would just open more abilitys for errors without any real benefit.

**Comment by Amerlander** [comment]
ok, I just finished my own test environment. The Pi actually is waiting before he starts the serial connection. Therefore it might be wise to keep the sync and send @START@ back and for.
Il just continue my tests and then we can discuss this further.

**Comment by rzbrk** [comment]
Okay, I understood that after flashing the Calliope Minin the CalliopEO.py script on the Raspberry Pi could basically immediately accept data from the Calliope Mini - right. However, in [programmMini()](https://github.com/calliope-edu/CalliopEO_AstroPi/blob/08135652390b6bf9f0ab1d5ca133930874e7ec97/CalliopEO.py#L192) the script waits for 20 seconds after flashing to give the Calliope sufficient time to reboot. From my experience, this time is way to long.
Maybe, we reduce the 20 seconds (or even skip this) and also drop the sending of @START@ by the CalliopEO.py. Instead, CalliopEO.py could change immediately in a "listening mode" and wait for data until a pre-defined timeout. We could also drop the [retrys](https://github.com/calliope-edu/CalliopEO_AstroPi/blob/08135652390b6bf9f0ab1d5ca133930874e7ec97/CalliopEO.py#L256) and just rely on the timeout. The retry would make sense, if we would reflash the Calliope or reestablish (disconnect/reconnect) the serial connection. But currently, this does not happen. Currently, a retry is basically waiting longer. But why not adjusting the timeout interval instead?

What are your thoughts about this?

**Comment by Amerlander** [comment]
We have this line `if len(lines) > ((MAX_DATA_SIZE * 1024 * 1024) / 17):`, which tries to guess the filesize. I thought it would just work without the division with 17, but the filesize was always wrong. So I have no clue why we have to devide here and its just a number which turned out to lead to nearly correct file sizes.

May need some improvement.

**Pull request merged**
